### ISSUE TITLE
Select only desired files and folder?

### ISSUE THREAD

**Issue by krigeta** [r12habh/Torrent-To-Google-Drive-Downloader#32]
Is it possible to download a certain file or folder or a combination of them?

**Comment by r12habh** [comment]
Can you be a bit more specific?

**Comment by krigeta** [comment]
> @krigeta
> Can you be a bit more specific?

like I want to download two seasons of anime season 1 and season 2 folder then in  those folders episodes are present then I need to download only selected episodes because I have some of them already. so its like folder consisting ten files but I want to download only two files from that folder and same goes for another folder.

- Main Folder
  -  season 1
  -1
  <del>  -2</del>
  <del>  -3</del>
  <del>  -4</del>
  -5
  -  season 2
  <del>  -2</del>
  -3
  <del>  -4</del>

**Comment by r12habh** [comment]
@krigeta 
That's why we store the downloaded files on google drive, where you decide which files you want to download locally. Simple.
You can also remove the files you don't want from GDrive only.

**Comment by krigeta** [comment]
Gdrive has limited storage, that's why I asked and not people are buying the storage. btw if you don't know how to do that it's okay.

issue is not resolved but the post is closed. 🤷‍♂️🤦‍♂️

**Comment by r12habh** [comment]
@krigeta
I do know how to do it
download the files in google colab instead of gdrive
then use shell scripts to move the files you need to gdrive 
done

the issue was marked closed coz that won't be solved with Python as there is no way to "download" only the necessary files
it's not a torrent client. 
this repo is just a bunch of scripts.

But you are welcome to try it, create a PR I'll merge it.
